# Generated by Django 5.2.17 on 2026-09-20 07:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategoriya ati')),
                ('order_index', models.CharField(max_length=3, verbose_name='Tartip nomeri')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Restoran Ati')),
                ('address', models.CharField(max_length=150, verbose_name='Manzili')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon nomeri')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv/Aktiv emes')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Tagam Ati')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tariypi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bahasi')),
                ('is_available', models.BooleanField(default=False, verbose_name='Qol jetimliligi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurant.category')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Ingredient ati')),
                ('unit', models.CharField(choices=[('kg', 'kilogramm'), ('l', 'litr')], max_length=12, verbose_name='Olshem birligi')),
                ('current_stock', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mugdari')),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurant.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='restoran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurant.restaurant'),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'IN'), ('out', 'OUT')])),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Mugdari')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transaction', to='restaurant.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=None, verbose_name='Stol nomeri')),
                ('guess_count', models.IntegerField(verbose_name='Orin sani')),
                ('status', models.CharField(choices=[('bos', 'Bos'), ('bant', 'Bant'), ('bronlangan', 'Bronlangan')], max_length=20, verbose_name='Halati')),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_serving', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Mugdari')),
                ('unit', models.CharField(choices=[('kg', 'Kilogramm'), ('gr', 'gramm'), ('mg', 'milligramm'), ('l', 'litr'), ('ml', 'ml'), ('none', 'olshem birligi')], default='none', max_length=10, verbose_name='olshem birligi')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recept_items', to='restaurant.dish')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient', to='restaurant.ingredient')),
            ],
            options={
                'verbose_name': 'Retsept elementi',
                'verbose_name_plural': 'Retsept elementlari',
                'unique_together': {('dish', 'ingredient')},
            },
        ),
    ]
