# Generated by Django 5.2.17 on 2026-09-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('bos', 'Bos'), ('bant', 'Bant')], max_length=20, verbose_name='Halati'),
        ),
    ]
