# Generated by Django 5.2.17 on 2026-09-20 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('USErs', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_count', models.IntegerField(default=1, verbose_name='Adam sani')),
                ('reservation_date', models.DateField(verbose_name='Sane(kun-ay-jil)')),
                ('reservation_time', models.TimeField(verbose_name='Saat(saat-minut)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('jaratildi', 'Jaratiw'), ('biykarlandi', 'Biykarlaw')], default='jaratildi', verbose_name='statusi')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reservations', to='USErs.customer')),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurant.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_reservations', to='restaurant.table')),
            ],
        ),
    ]
