# Generated by Django 5.2.17 on 2026-09-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('jaratildi', 'Jaratildi'), ('jawildi', 'Jawildi'), ('tastiyiqlandi', 'Tastiyiqlandi'), ('biykar_etildi', 'Biykar etiw')], default='jaratildi', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='duration_hours',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guests_count',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
