# Generated by Django 5.2.17 on 2026-09-22 17:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('USErs', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Q', 'Qabillandi'), ('CL', 'Jabildi')], default='Q', max_length=10, verbose_name='Statusi')),
                ('paymend_method', models.CharField(choices=[('cash', 'Cash'), ('credit card', 'Credit Card'), ('Tolew turi', 'Tolem turin tanlan')], default='Tolem turi', max_length=20, verbose_name='Tolem turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='USErs.customer')),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.restaurant')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.table')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='USErs.xizmetker', verbose_name='Officiant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Qosimdsha jaziw ushin')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sani')),
                ('status', models.CharField(choices=[('J', '🆕 Jana'), ('AJ', '👨\u200d🍳 Aspazxanaga jiberildi'), ('TA', '⏳ Tayyarlanbaqta'), ('T', '✅ Tayyar')], default='J', max_length=50, verbose_name='Statusi')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurant.dish', verbose_name='Tagam')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
            ],
        ),
    ]
