# Generated by Django 5.2.17 on 2026-09-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reservation',
        ),
    ]
